[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "discord-py>=2.5.2",
    "flask>=3.1.1",
    "yt-dlp>=2025.6.25",
]
